# """
# app/reports/router.py
# ======================
# Reports Module — FastAPI Router

# Implements the spec'd API endpoints:
#     POST /reports/generate     Generate a report from company documents
#     GET  /reports              List all saved reports for a company

# Reports are generated by:
# 1. Retrieving relevant document chunks from Supabase Vector
# 2. Sending chunks to Gemini with a report-specific prompt
# 3. Saving the result to the `reports` table
# 4. Returning the structured report to the client
# """

# import uuid
# import json
# from fastapi import APIRouter, HTTPException, Query
# from datetime import datetime, timezone

# from app.reports.schemas import (
#     ReportGenerateRequest,
#     ReportGenerateResponse,
#     ReportListResponse,
#     ReportRecord,
#     ReportContent,
# )
# from app.rag.services.retriever import retrieve_relevant_chunks
# from core.gemini_client import get_chat_model
# from core.supabase_client import get_supabase_client

# router = APIRouter()


# # ---------------------------------------------------------------------------
# # Report type → AI prompt topic mapping
# # ---------------------------------------------------------------------------

# REPORT_PROMPTS = {
#     "management_summary": (
#         "Generate a comprehensive management summary of the company's current status. "
#         "Cover overall business health, key risks, and top recommendations for leadership."
#     ),
#     "hr_compliance": (
#         "Analyse HR documents and identify compliance issues. "
#         "Look for missing employee files, policy violations, attendance problems, "
#         "and NTE candidates. List all findings with evidence."
#     ),
#     "sales_performance": (
#         "Analyse sales data and performance reports. "
#         "Identify top and bottom performing products, staff, or branches. "
#         "Highlight revenue opportunities and areas needing improvement."
#     ),
#     "logistics": (
#         "Analyse logistics and fleet data. "
#         "Identify overdue PMS schedules, delivery delays, driver issues, "
#         "and client delivery performance."
#     ),
#     "pms": (
#         "Analyse equipment and vehicle maintenance records. "
#         "Identify all equipment overdue for PMS, upcoming schedules, "
#         "and maintenance risks."
#     ),
#     "risk": (
#         "Identify all high and critical risk issues across all company documents. "
#         "List every finding that requires immediate management attention, "
#         "with evidence, business impact, and recommended action."
#     ),
# }

# REPORT_TITLES = {
#     "management_summary": "Management Summary Report",
#     "hr_compliance": "HR Compliance Report",
#     "sales_performance": "Sales Performance Report",
#     "logistics": "Logistics Report",
#     "pms": "PMS & Maintenance Report",
#     "risk": "Risk Report",
# }

# # ---------------------------------------------------------------------------
# # Report generation system prompt
# # ---------------------------------------------------------------------------

# REPORT_SYSTEM_PROMPT = """
# You are NexVision Reporting AI.
# You generate structured business reports from company documents.

# STRICT RULES:
# 1. Use ONLY the provided document context. Do not use outside knowledge.
# 2. Do not invent facts. If data is missing, say so in key_findings.
# 3. Always cite the source document for every finding.
# 4. Write in clear, professional business English.
# 5. Be direct and decision-focused.

# Return ONLY valid JSON matching this exact structure — no markdown, no extra text:

# {
#   "summary": "Executive summary of findings in 2-3 sentences.",
#   "key_findings": [
#     "Finding 1 with source citation",
#     "Finding 2 with source citation"
#   ],
#   "risks": [
#     "Risk 1 identified from documents",
#     "Risk 2 identified from documents"
#   ],
#   "recommendations": [
#     "Recommendation 1 with action owner and timeline",
#     "Recommendation 2 with action owner and timeline"
#   ],
#   "sources": [
#     "filename.pdf, page 1",
#     "spreadsheet.xlsx, Sheet: Q3"
#   ]
# }
# """.strip()


# # ---------------------------------------------------------------------------
# # Helper: call Gemini to generate report content
# # ---------------------------------------------------------------------------

# async def _generate_report_content(
#     topic: str,
#     chunks: list,
# ) -> ReportContent:
#     """
#     Build a report prompt from retrieved chunks and call Gemini.

#     Args:
#         topic: The report-specific analysis question.
#         chunks: Retrieved document chunks from Supabase Vector.

#     Returns:
#         ReportContent: Structured report with findings, risks, recommendations.
#     """

#     # Format chunks into context block
#     context = "\n\n".join([
#         f"[SOURCE: {c.source_file}, Page {c.page_number or 'N/A'}]\n{c.chunk_text}"
#         for c in chunks
#     ])

#     full_prompt = (
#         f"{REPORT_SYSTEM_PROMPT}\n\n"
#         f"DOCUMENT CONTEXT:\n{context}\n\n"
#         f"REPORT TASK: {topic}\n\n"
#         f"Respond with ONLY valid JSON. No markdown."
#     )

#     # Call Gemini
#     model = get_chat_model()
#     response = model.generate_content(full_prompt)

#     if not response.text:
#         raise HTTPException(
#             status_code=500,
#             detail="Gemini returned an empty response. Please try again."
#         )

#     # Clean and parse JSON
#     import re
#     raw = response.text.strip()
#     raw = re.sub(r"```(?:json)?\s*", "", raw).strip()
#     raw = re.sub(r"```\s*$", "", raw).strip()

#     try:
#         parsed = json.loads(raw)
#         return ReportContent(**parsed)
#     except (json.JSONDecodeError, Exception) as e:
#         raise HTTPException(
#             status_code=500,
#             detail=f"Failed to parse report content from AI: {e}"
#         )


# # ---------------------------------------------------------------------------
# # POST /reports/generate
# # ---------------------------------------------------------------------------

# @router.post(
#     "/reports/generate",
#     response_model=ReportGenerateResponse,
#     summary="Generate a business report",
#     description=(
#         "Generates a structured business report from uploaded company documents.\n\n"
#         "**Available report types:**\n"
#         "- `management_summary` — Overall business health\n"
#         "- `hr_compliance` — HR policy and compliance issues\n"
#         "- `sales_performance` — Sales trends and performance\n"
#         "- `logistics` — Delivery and fleet status\n"
#         "- `pms` — Equipment maintenance schedule\n"
#         "- `risk` — All high and critical risk findings\n\n"
#         "The report is saved to the `reports` table and returned in the response."
#     ),
# )
# async def generate_report(request: ReportGenerateRequest):
#     """
#     Generate a structured report from company documents.

#     1. Retrieves relevant document chunks from Supabase Vector
#     2. Sends chunks to Gemini with a report-specific prompt
#     3. Saves the report to the `reports` table
#     4. Returns the structured report
#     """

#     # Get the topic and default title for this report type
#     topic = REPORT_PROMPTS.get(request.report_type.value, "Summarise all company documents.")
#     default_title = REPORT_TITLES.get(request.report_type.value, "Business Report")
#     final_title = request.title if request.title else default_title

#     # Step 1: Retrieve relevant chunks
#     chunks = await retrieve_relevant_chunks(
#         question=topic,
#         company_id=request.company_id,
#         top_k=request.top_k,
#     )

#     if not chunks:
#         raise HTTPException(
#             status_code=404,
#             detail=(
#                 f"No AI-ready documents found for company '{request.company_id}'. "
#                 "Upload and process documents before generating reports."
#             ),
#         )

#     # Step 2: Generate report content via Gemini
#     content = await _generate_report_content(topic=topic, chunks=chunks)

#     # Step 3: Save to reports table
#     report_id = str(uuid.uuid4())
#     sb = get_supabase_client()

#     try:
#         sb.table("reports").insert({
#             "id": report_id,
#             "company_id": request.company_id,
#             "report_type": request.report_type.value,
#             "title": final_title,
#             "content": content.model_dump(),
#             "generated_by": request.user_id,
#             "created_at": datetime.now(timezone.utc).isoformat(),
#         }).execute()
#     except Exception as e:
#         print(f"[WARN] Could not save report to DB: {e}")

#     return ReportGenerateResponse(
#         report_id=report_id,
#         company_id=request.company_id,
#         report_type=request.report_type.value,
#         title=final_title,
#         content=content,
#         generated_by=request.user_id,
#         message=f"'{final_title}' generated successfully from {len(chunks)} document segments.",
#     )


# # ---------------------------------------------------------------------------
# # GET /reports
# # ---------------------------------------------------------------------------

# @router.get(
#     "/reports",
#     response_model=ReportListResponse,
#     summary="List all saved reports",
#     description="Returns all previously generated reports for a company, newest first.",
# )
# async def list_reports(
#     company_id: str = Query(..., description="UUID of the company"),
#     limit: int = Query(default=20, ge=1, le=100, description="Max number of reports to return"),
# ):
#     """
#     Retrieve all saved reports for a company.
#     Ordered by most recent first.
#     """
#     sb = get_supabase_client()

#     try:
#         result = (
#             sb.table("reports")
#             .select("*")
#             .eq("company_id", company_id)
#             .order("created_at", desc=True)
#             .limit(limit)
#             .execute()
#         )
#     except Exception as e:
#         raise HTTPException(status_code=500, detail=str(e))

#     records = []
#     for r in result.data or []:
#         raw_content = r.get("content", {})
#         if isinstance(raw_content, str):
#             try:
#                 raw_content = json.loads(raw_content)
#             except Exception:
#                 raw_content = {}

#         records.append(
#             ReportRecord(
#                 id=r["id"],
#                 company_id=r["company_id"],
#                 report_type=r["report_type"],
#                 title=r["title"],
#                 content=ReportContent(**raw_content),
#                 generated_by=r.get("generated_by", ""),
#                 created_at=str(r.get("created_at", "")),
#             )
#         )

#     return ReportListResponse(
#         company_id=company_id,
#         reports=records,
#         total=len(records),
#     )